# ----------------------------------------------------------------------------------------------
# Script to predict IOD for remaining DGRP lines
# Data generated by Felix P Leiva, Radboud University
# Created by Felix P Leiva (20190604)
# Modifications: 
# ----------------------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls()) 
today<-format(Sys.Date(),"%Y%m%d")
#------------------------------------------------------------------------------------------------------------
#get working directory
setwd("C:/Users/Invunche/Dropbox/Radboud University/publicaciones/Thesis/3. Thermal tolerance on big and small cells/datos/size traits")
setwd("C:/Users/fleiva/Dropbox/Radboud University/publicaciones/Thesis/3. Thermal tolerance on big and small cells/datos/size traits")
getwd()# check directory
#------------------------------------------------------------------------------------------------------------
#Libraries
library(ggplot2)
library(gridExtra)
library(nlme)
library(lme4)
library(car)
library(multcomp)
library(visreg)
library(emmeans)
library(PerformanceAnalytics)
library(lattice)
library(MuMln)
#------------------------------------------------------------------------------------------------------------
#Reading cell size data
datos.20<-read.csv("Individual body traits (no iod) for all DGRP lines.csv")
datos.14<-read.csv("Individual body traits for 14 DGRP lines.csv")
datos.14<-subset(datos.14,datos.14$stock!=25203)#doubting about the accurate of the measurements

#------------------------------------------------------------------------------------------------------------
#Selecting columns of interest
names(datos.20)
datos.20<-datos.20[c(2:9,12,13)]
names(datos.14)
datos.14<-datos.14[c(2:9,12:14)]
#------------------------------------------------------------------------------------------------------------
#Transforming variables wrongly assigned (ONLY IF NECCESARY)
str(datos.20)
datos.20$stock<-as.factor(datos.20$stock) 
datos.20$age<-as.numeric(datos.20$age) 
datos.20$plate<-as.factor(datos.20$plate) 
str(datos.14)
datos.14$stock<-as.factor(datos.14$stock) 
datos.14$age<-as.numeric(datos.14$age) 
datos.14$plate<-as.factor(datos.14$plate) 
#------------------------------------------------------------------------------------------------------------
#Predicting IOD for the remaining six stocks. For this, I will explore what traits
#shows high correlations with the observed data of iod

#Subsetting data by sex
#
male.20<-subset(datos.20,datos.14$sex=="male")
female.20<-subset(datos.20,datos.14$sex!="male")

male.14<-subset(datos.14,datos.14$sex=="male")
female.14<-subset(datos.14,datos.14$sex!="male")

male.rem<-male.20[ !(male.20$stock %in% male.14$stock), ]
female.rem<-female.20[ !(female.20$stock %in% female.14$stock), ]#subtract two dataframes

#Plotting correlations
chart.Correlation(male.14[7:11])#male
chart.Correlation(female.14[7:11])#female

# Modeling with random effects (stock)
#females
fit.female<-lmer(iod~ws+(1|stock),data = female.14)
coef(summary(fit.female))[ , "Estimate"];r.squaredGLMM(fit.female)

#males
fit.male<-lmer(iod~ws+(1|stock),data = male.14)
coef(summary(fit.male))[ , "Estimate"];r.squaredGLMM(fit.male)


#Predicting iod for males
names(male.rem)
male.rem$iod<-predict(fit.male,newdata=male.rem,re.form=NA)

#Predicting iod for females
names(female.rem)
female.rem$iod<-predict(fit.female,newdata=female.rem,re.form=NA)

#merging the dataframes
TableS1<-rbind(datos.14,female.rem,male.rem)
xtabs(formula = ~stock+sex,data = TableS1)
#Export dataframe
TableS1 <- TableS1[-c(161),]
setwd("C:/Users/Invunche/Dropbox/Radboud University/publicaciones/Thesis/3. Thermal tolerance on big and small cells/manuscritos/Submission FE")

# Rescale all variables (z-scores, just to visualize in a better way the data) by sex
female<-subset(TableS1,TableS1$sex=="female")#females
male<-subset(TableS1,TableS1$sex=="male")#males
#female
female$fresh.mass.z<-scale(female$fw)
female$iod.z<-scale(female$iod)
female$wing.area.z<-scale(female$ws)
female$cell.number.z<-scale(female$cell.number)
female$cell.area.z<-scale(female$cell.area)

# male
male$fresh.mass.z<-scale(male$fw)
male$iod.z<-scale(male$iod)
male$wing.area.z<-scale(male$ws)
male$cell.number.z<-scale(male$cell.number)
male$cell.area.z<-scale(male$cell.area)

TableS1<-rbind(female,male)
#write.csv(TableS1,"Phenotypic traits data of DGRP lines.csv",row.names = FALSE)
#------------------------------------------------------------------------------------------------------------
##############################END OF SCRIPT#####################################
#------------------------------------------------------------------------------------------------------------