# -------------------------------------------------------------------------------------
# Script to analyse the effect of body size-related traits on survival time of 
# DGRP lines
# Data generated by Felix P Leiva, Radboud University
# Created by Felix P Leiva
# -------------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# -------------------------------------------------------------------------------------
setwd("C:/Users/Invunche/Dropbox/Radboud University/publicaciones/Thesis/3. Thermal tolerance on big and small cells/manuscritos/Submission FE")
getwd()# check directory
# -------------------------------------------------------------------------------------
#Libraries (we do NOT need to install all these packages)
library(xlsx)
library(lme4)
library(nlme)
library(car)
library(visreg)
library(MuMIn)
library(AICcmodavg)
library(ggplot2)
library(dplyr)
library(tidyr)
library(plyr)
library(MASS)
# library(readxl)
# library(httr)
# -------------------------------------------------------------------------------------
#Load data of normoxia (20 lines)
all.lines.21<-read.csv("Survival time of Drosophila melanogaster and its associated size traits at 21 kPa.csv")
#Load data of hypoxia (6 lines)
all.lines.hypo<-read.csv("Survival time of Drosophila melanogaster and its associated size traits at two oxygen levels.csv")
# -------------------------------------------------------------------------------------
# First, I will calculate the median survival time for each of the 
# stress temperatures. Because females and males differed evidently
# in all size traits  measured (males smaller than females, Table S1 of the 
# paper), we calculated the median by sex. Although with this approximation much 
# information is lost,it is necessary to do so because we do not have measurements
# in each of the size traits at the individual level (only at the level of the 
# stock). Ignoring this critical point, we would be violating one of the 
# statistical principles, statistical independence, by creating pseudo-
# replicates and consequently leading us to erroneous conclusions.
# -------------------------------------------------------------------------------------
#select by sex
male.21<-filter(all.lines.21,sex=="male") 
female.21<-filter(all.lines.21,sex!="male")
male.hypo<-filter(all.lines.hypo,sex=="male")
female.hypo<-filter(all.lines.hypo,sex!="male")
# -------------------------------------------------------------------------------------
# STEP 1: FEMALES
# -------------------------------------------------------------------------------------
#median of traits per stock (median instead of mean to be consistent with Figure 2 (box plot) of the paper; 
female21.mean=aggregate(surv.time~test.temp+cell.area+cell.number+stock+genotype+iod+fw+ws,female.21,median)

#see data structure
str(female21.mean)
female21.mean$stock<-as.factor(female21.mean$stock)
female21.mean$test.temp<-as.numeric(female21.mean$test.temp)

#Full model with biologically relevant interactions
f21a<-gls(surv.time~
            scale(test.temp)
          +scale(test.temp)*scale(fw)
          +scale(test.temp)*scale(iod)
          +scale(test.temp)*scale(ws)
          +scale(test.temp)*scale(cell.number)
          +scale(test.temp)*scale(cell.area)
          ,data=female21.mean,na.action = na.omit,method = "ML")

#Assess potential correlations by using VIF (variance inflation factor). This function 
#allows identifying for multicollinearity (i.e. correlations between predictive 
#variables in the model). As consensus, I used VIF higher than 5 (VIF> 5) as evidence of
#multicollinearity. 

vif(f21a)#exclude wing area (ws) VIF> 5

# We clearly see that the VIFs are very high for those variables related
# to wing size (wing area, cell area or cell number). This is due to the 
# "circularity" generated by the calculation, e.g., of the number of cells or cell area
# (see description in the methods section ). Let's see what happens with the VIF when we 
# exclude the wing size (ws) from the model.

# Re-run

f21b<-gls(surv.time~
            scale(test.temp)
          +scale(test.temp)*scale(fw)
          +scale(test.temp)*scale(iod)
          #+scale(test.temp)*scale(ws)
          +scale(test.temp)*scale(cell.number)
          +scale(test.temp)*scale(cell.area)
          ,data=female21.mean,na.action = na.omit,method = "ML")

vif(f21b) # all VIF below 5---> OK!!
f21b=stepAIC(f21b)

#refit the model with "REML" to get more precise estimates and no scaling the
#variables
f21c <- gls(surv.time ~ test.temp * fw + iod,
            na.action = na.omit,method="REML",data=female21.mean)

anova(f21c)

#remove non significant variables and run again
f21c <- gls(surv.time ~ test.temp + fw + iod,
            na.action = na.omit,method="REML",data=female21.mean) #Model from Table 1
#run again
anova(f21c)

#               numDF   F-value p-value
# (Intercept)          1 12235.039  <.0001
# scale(test.temp)     1   801.093  <.0001
# scale(fw)            1     5.189  0.0256
# scale(iod)           1     6.710  0.0115

summary(f21c)$tTable

#                   Value   Std.Error   t-value     p-value
# (Intercept) 16.476454810 0.647775539  25.435438 2.555930e-38
# test.temp   -0.373103224 0.013182190 -28.303584 1.950235e-41
# fw           0.354803354 0.104255840   3.403199 1.078006e-03
# iod         -0.002631578 0.001015926  -2.590325 1.154218e-02


# CONCLUSION I: After account for putative correlations (VIFs) among our predictor variables,
# we found no evidence of cell size affecting survival time of Drosophila melanogaster'
# females. By the contrary, our most informative model considered test temperature (negative effect),
# fresh mass (fw, positive effect) and interocular distance (negative effect) as the predictive variables. 
# -------------------------------------------------------------------------------------
# STEP 2: MALES
# -------------------------------------------------------------------------------------
# Let now do repeat the same analyses for males.
# 
male21.mean=aggregate(surv.time~test.temp+cell.area+cell.number+stock+genotype+iod+fw+ws,male.21,median)

m21a<-gls(surv.time~
            scale(test.temp)
          +scale(test.temp)*scale(fw)
          +scale(test.temp)*scale(iod)
          +scale(test.temp)*scale(ws)
          +scale(test.temp)*scale(cell.number)
          +scale(test.temp)*scale(cell.area)
          ,data=male21.mean,na.action = na.omit,method = "ML")

vif(m21a)#exclude wing area (ws) VIF> 5 (See Table S7 of the MS)

# Re-run
m21b<-gls(surv.time~
            scale(test.temp)
          +scale(test.temp)*scale(fw)
          +scale(test.temp)*scale(iod)
          #+scale(test.temp)*scale(ws)
          +scale(test.temp)*scale(cell.number)
          +scale(test.temp)*scale(cell.area)
          ,data=male21.mean,na.action = na.omit,method = "ML")

vif(m21b) # all VIF below 5---> OK!! (See Table S7 of the MS)
m21b=stepAIC(m21b)

 
#refit the model with "REML" to get more precise estimates and no scaling the
#variables
m21c <- gls(surv.time ~ test.temp * cell.area + fw, 
            na.action = na.omit, method="REML",data=male21.mean)

anova(m21c) # ANOVA Type I

#                       numDF   F-value p-value
# (Intercept)             1 11500.527  <.0001
# test.temp               1   491.852  <.0001
# cell.area               1     0.905  0.3446
# fw                      1     5.464  0.0221
# test.temp:cell.area     1     2.576  0.1127

summary(m21c)

#remove non significant variables and run again
m21c <- gls(surv.time ~ test.temp + fw, 
            na.action = na.omit, method="REML",data=male21.mean)# Model in Table 1

anova(m21c) # ANOVA Type I
#              numDF   F-value p-value
# (Intercept)     1 11416.507  <.0001
# test.temp       1   488.258  <.0001
# fw              1     6.332  0.0139

summary(m21c)
# Coefficients:
#                   Value Std.Error    t-value p-value
# (Intercept) 12.462405 0.5178295  24.066617  0.0000
# test.temp   -0.297254 0.0134525 -22.096568  0.0000
# fw           0.381354 0.1515543   2.516287  0.0139

# CONCLUSION II: After account for putative correlations (VIFs) among our predictor variables,
# we found our most informative model considered fresh mass (fw, positive effect), the 
# test temperature as the predictive variables. 
# # -------------------------------------------------------------------------------------
# So far, I do have conducted several analyses that seek to answer the question 
# about what body size-related variables (fresh mass, wing size, 
# number of cells and cell size) allow us to predict, both for females and males,
# the survival at high temperatures Drosophila melanogaster. As an additional variable, 
# I will test the effects of genome size. The data for this variable are part
# of the article by Ellis et al 2014 (Plos Genetics 10 (7), e1004522) and are available 
# only for female individuals. The reasoning behind its inclusion relates cell 
# size is correlated positively with genome size, so we have same predictions as for cell size. 
# Again I will apply the same approach, but adding genome size. 
# -------------------------------------------------------------------------------------
# load genome size data from Ellis et al 2014 Plos Genetics 10(7), e1004522
# url1<-'https://doi.org/10.1371/journal.pgen.1004522.s004'
# p1f <- tempfile()
# download.file(url1, p1f, mode="wb")
# genome.ellis<-read_excel(path = p1f, sheet = 1)
# # # # -------------------------------------------------------------------------------------
# # # # Rename columns
# names(genome.ellis)[names(genome.ellis) == "Avg Mb"] <- "genome.mean.mb"
# names(genome.ellis)[names(genome.ellis) == "SE"] <- "genome.mean.se"
# names(genome.ellis)[names(genome.ellis) == "Sex"] <- "sex"
# # # # Create a new column: "genotype"
# genome.ellis$DGRP<-substring(genome.ellis$Strain,1,4)
# genome.ellis$numberid<-substring(genome.ellis$Strain,6)
# genome.ellis$genotype<-paste(genome.ellis$DGRP,genome.ellis$numberid,sep = "-")
# names(genome.ellis)
# # # 
# #genome size only for females of D. melanogaster
# genome.ellis<-genome.ellis[c(2:4,8)]
# # # 
# # convert to DNA content (picograms) following Dolezel et al 2003
# genome.ellis$genome.pg<-genome.ellis$genome.mean.mb/978
# genome.ellis<-genome.ellis[c(4,5)]
# 
# #merge genome size data con other traits
# female21.mean.genome<-merge(female21.mean,genome.ellis,by="genotype")
# write.csv(female21.mean.genome,paste("Survival time of Drosophila melanogaster (females) and its associated size traits at 21 kPa (+genome size).csv",sep=""),row.names = F)
female21.mean.genome<-read.csv("Survival time of Drosophila melanogaster (females) and its associated size traits at 21 kPa (+genome size).csv")
# -------------------------------------------------------------------------------------
# STEP III: FEMALES (SIZE TRAITS + GENOME SIZE)
# -------------------------------------------------------------------------------------
f21ag<-gls(surv.time~
            scale(test.temp)
          +scale(test.temp)*scale(fw)
          +scale(test.temp)*scale(iod)
          +scale(test.temp)*scale(ws)
          +scale(test.temp)*scale(cell.number)
          +scale(test.temp)*scale(cell.area)
          +scale(test.temp)*scale(genome.pg)
          ,data=female21.mean.genome,na.action = na.omit,method = "ML")

vif(f21ag)#exclude wing area (ws) VIF> 5 (See Table S7 of the MS)

# Re-run
f21bg<-gls(surv.time~
            scale(test.temp)
          +scale(test.temp)*scale(fw)
          +scale(test.temp)*scale(iod)
          #+scale(test.temp)*scale(ws)
          +scale(test.temp)*scale(cell.number)
          +scale(test.temp)*scale(cell.area)
          +scale(test.temp)*scale(genome.pg)
          ,data=female21.mean.genome,na.action = na.omit,method = "ML")

vif(f21bg) # all VIFs below 5---> OK!!
f21bg=stepAIC(f21bg)

f21cg <- gls(surv.time ~ test.temp * fw + iod, 
            na.action = na.omit, method="REML",data=female21.mean.genome)
anova(f21cg)

#remove the non significant variables
f21cg <- gls(surv.time ~ test.temp + fw + iod, 
             na.action = na.omit, method="REML",data=female21.mean.genome)
anova(f21cg)

# I do end up with the identical results (see "CONCLUSION I")...

# CONCLUSION III:genome size does not improve the model fit
################################################################################
#STEP IV: EFFECT OF HYPOXIA IN FEMALES
################################################################################
female.hypo.mean=aggregate(cbind(surv.time)~test.temp+cell.area+cell.number+stock+iod+fw+ws+test.oxygen,female.hypo,median)
female.hypo.mean<-merge(female21.mean.genome,female.hypo.mean,by="stock")#females
female.hypo.mean=aggregate(surv.time.x~stock+test.temp.x+test.oxygen+cell.area.x+cell.number.x+iod.x+fw.x+ws.x+genome.pg,female.hypo.mean,median)
names(female.hypo.mean)

#Rename column
names(female.hypo.mean)
names(female.hypo.mean)[c(2,4:8,10)] = c("test.temp","cell.area","cell.number","iod",
                                     "fw","ws","surv.time")

str(female.hypo.mean)
female.hypo.mean$stock<-as.factor(female.hypo.mean$stock)
female.hypo.mean$test.temp<-as.numeric(female.hypo.mean$test.temp)
female.hypo.mean$test.oxygen<-as.numeric(female.hypo.mean$test.oxygen)

# repeat same analyses as before, but this time adding "test.oxygen" as a predictor
# I dot have any expectation on cell number effects under hypoxia
fhypoa<-gls(surv.time~
              scale(test.temp)
            +scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(fw)
            +scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(test.oxygen)*scale(iod)
            +scale(test.oxygen)*scale(iod)
            +scale(test.temp)*scale(iod)
            +scale(test.temp)*scale(test.oxygen)*scale(ws)
            +scale(test.oxygen)*scale(ws)
            +scale(test.temp)*scale(ws)
            # +scale(test.temp)*scale(test.oxygen)*scale(cell.number)
            # +scale(test.oxygen)*scale(cell.number)
            # +scale(test.temp)*scale(cell.number)
            +scale(test.temp)*scale(test.oxygen)*scale(cell.area)
            +scale(test.oxygen)*scale(cell.area)
            +scale(test.temp)*scale(cell.area)
            ,data=female.hypo.mean,na.action = na.omit,method = "ML")


vif(fhypoa)#exclude wing area (ws) VIF> 5

# Re-run
fhypob<-gls(surv.time~
              scale(test.temp)
            +scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(fw)
            +scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(test.oxygen)*scale(iod)
            +scale(test.oxygen)*scale(iod)
            +scale(test.temp)*scale(iod)
            # +scale(test.temp)*scale(test.oxygen)*scale(ws)
            # +scale(test.oxygen)*scale(ws)
            # +scale(test.temp)*scale(ws)
            # +scale(test.temp)*scale(test.oxygen)*scale(cell.number)
            # +scale(test.oxygen)*scale(cell.number)
            # +scale(test.temp)*scale(cell.number)
            +scale(test.temp)*scale(test.oxygen)*scale(cell.area)
            +scale(test.oxygen)*scale(cell.area)
            +scale(test.temp)*scale(cell.area)
            ,data=female.hypo.mean,na.action = na.omit,method = "ML")

vif(fhypob) # all VIF below 5---> OK!!
fhypob=stepAIC(fhypob)

#refit the model with "REML" to get more precise estimates and no scaling the
#variables

fhypoc<-gls(surv.time~test.temp + fw + iod,
            data=female.hypo.mean,na.action = na.omit,method = "REML")

anova(fhypoc)

 
# numDF  F-value p-value
# (Intercept)     1 9226.970  <.0001
# test.temp       1  717.309  <.0001
# fw              1    0.238  0.6284
# iod             1    8.198  0.0064

#exclude the non significant variables and run again
fhypoc<-gls(surv.time~test.temp + iod,
            data=female.hypo.mean,na.action = na.omit,method = "REML")

anova(fhypoc)
 
#             numDF  F-value p-value
# (Intercept)     1 8990.603  <.0001
# test.temp       1  698.934  <.0001
# iod             1    6.092  0.0174

summary(fhypoc)$tTable
#                    Value    Std.Error   t-value      p-value
# (Intercept) 17.424780532 0.6402088586  27.21734 1.374467e-29
# test.temp   -0.402595092 0.0152282672 -26.43735 4.716706e-29
# iod         -0.001478065 0.0005988239  -2.46828 1.744200e-02


# CONCLUSION IV: After account for putative correlations (vifs) among our predictor variables,
# we found no evidence of oxygen affecting survival time of Drosophila melanogaster'
# females. By the contrary, our most informative model considered interocular distance 
# (iod, negative effect) and test temperature (also negative effect) as the predictive variables.    
################################################################################
# STEP V: EFFECT OF HYPOXIA IN MALES
################################################################################
male.hypo.mean=aggregate(cbind(surv.time)~test.temp+cell.area+cell.number+stock+iod+fw+ws+test.oxygen,male.hypo,median)
names(male.hypo.mean)

str(male.hypo.mean)
male.hypo.mean$stock<-as.factor(male.hypo.mean$stock)
male.hypo.mean$test.temp<-as.numeric(male.hypo.mean$test.temp)
male.hypo.mean$test.oxygen<-as.numeric(male.hypo.mean$test.oxygen)

# repeat same analyses as for females in hypoxia (I dot have any expectation on cell number effects under hypoxia)

mhypoa<-gls(surv.time~
              scale(test.temp)
            +scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(fw)
            +scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(test.oxygen)*scale(iod)
            +scale(test.oxygen)*scale(iod)
            +scale(test.temp)*scale(iod)
            +scale(test.temp)*scale(test.oxygen)*scale(ws)
            +scale(test.oxygen)*scale(ws)
            +scale(test.temp)*scale(ws)
            # +scale(test.temp)*scale(test.oxygen)*scale(cell.number)
            # +scale(test.oxygen)*scale(cell.number)
            # +scale(test.temp)*scale(cell.number)
            +scale(test.temp)*scale(test.oxygen)*scale(cell.area)
            +scale(test.oxygen)*scale(cell.area)
            +scale(test.temp)*scale(cell.area)
            ,data=male.hypo.mean,na.action = na.omit,method = "ML")

vif(mhypoa)#exclude wing area (ws) VIF> 5

# Re-run
mhypob<-gls(surv.time~
              scale(test.temp)
            +scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)
            +scale(test.temp)*scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(fw)
            +scale(test.oxygen)*scale(fw)
            +scale(test.temp)*scale(test.oxygen)*scale(iod)
            +scale(test.oxygen)*scale(iod)
            +scale(test.temp)*scale(iod)
            # +scale(test.temp)*scale(test.oxygen)*scale(ws)
            # +scale(test.oxygen)*scale(ws)
            # +scale(test.temp)*scale(ws)
            # +scale(test.temp)*scale(test.oxygen)*scale(cell.number)
            # +scale(test.oxygen)*scale(cell.number)
            # +scale(test.temp)*scale(cell.number)
            +scale(test.temp)*scale(test.oxygen)*scale(cell.area)
            +scale(test.oxygen)*scale(cell.area)
            +scale(test.temp)*scale(cell.area)
            ,data=male.hypo.mean,na.action = na.omit,method = "ML")


vif(mhypob) # all VIF close to 5---> OK!!
mhypob=stepAIC(mhypob)

#refit the model with "REML" to get more precise estimates and without scaling the
#variables

mhypoc<-gls(surv.time~ test.temp*test.oxygen + test.temp*fw + test.temp*iod + 
              test.oxygen*cell.area,
              data=male.hypo.mean,na.action = na.omit,method = "REML")

anova(mhypoc)

#                         numDF  F-value p-value
# (Intercept)               1 7845.496  <.0001
# test.temp                 1  343.808  <.0001
# test.oxygen               1    4.808  0.0349
# fw                        1    0.003  0.9586
# iod                       1    2.903  0.0970
# cell.area                 1    0.460  0.5017
# test.temp:test.oxygen     1   13.085  0.0009
# test.temp:fw              1    5.365  0.0263
# test.temp:iod             1    1.528  0.2244
# test.oxygen:cell.area     1    8.538  0.0060

#exclude non significant variables
mhypoc<-gls(surv.time~ test.temp*test.oxygen,
            data=male.hypo.mean,na.action = na.omit,method = "REML")#Model in Table 1

anova(mhypoc)
# (Intercept)               1 6083.486  <.0001
# test.temp                 1  266.593  <.0001
# test.oxygen               1    3.728  0.0603
# test.temp:test.oxygen     1   10.637  0.0022
summary(mhypoc)$tTable
#                           Value    Std.Error   t-value      p-value
# (Intercept)            5.98303630 2.014878205  2.969428 0.004914073
# test.temp             -0.12143275 0.053598727 -2.265590 0.028693343
# test.oxygen            0.40024809 0.120651731  3.317384 0.001882496
# test.temp:test.oxygen -0.01047526 0.003211881 -3.261410 0.002204149

# CONCLUSION V: After account for putative correlations (vifs) among our predictor variables,
# we do not found evidence of cell size affecting survival time of Drosophila melanogaster'
# males. By the contrary, our most informative model considered test temperature 
# (negative effect), oxygen (positive effects) and their interaction (negative but non significant). 
# -------------------------------------------------------------------------------------
# STEP VI: EFFECT OF HYPOXIA IN FEMALES (SIZE TRAITS + GENOME SIZE)
# -------------------------------------------------------------------------------------
fhypoag<-gls(surv.time~
               scale(test.temp)
             +scale(test.oxygen)
             +scale(test.temp)*scale(test.oxygen)
             +scale(test.temp)*scale(test.oxygen)*scale(fw)
             +scale(test.temp)*scale(fw)
             +scale(test.oxygen)*scale(fw)
             +scale(test.temp)*scale(test.oxygen)*scale(iod)
             +scale(test.oxygen)*scale(iod)
             +scale(test.temp)*scale(iod)
             +scale(test.temp)*scale(test.oxygen)*scale(ws)
             +scale(test.oxygen)*scale(ws)
             +scale(test.temp)*scale(ws)
             # +scale(test.temp)*scale(test.oxygen)*scale(cell.number)
             # +scale(test.oxygen)*scale(cell.number)
             # +scale(test.temp)*scale(cell.number)
             +scale(test.temp)*scale(test.oxygen)*scale(cell.area)
             +scale(test.oxygen)*scale(cell.area)
             +scale(test.temp)*scale(cell.area)
             +scale(test.temp)*scale(test.oxygen)*scale(genome.pg)
             +scale(test.oxygen)*scale(genome.pg)
             +scale(test.temp)*scale(genome.pg)
           ,data=female.hypo.mean,na.action = na.omit,method = "ML")

vif(fhypoag)#exclude wing area and genome size VIF> 5

# Re-run
fhypobg<-gls(surv.time~
               scale(test.temp)
             +scale(test.oxygen)
             +scale(test.temp)*scale(test.oxygen)
             +scale(test.temp)*scale(test.oxygen)*scale(fw)
             +scale(test.temp)*scale(fw)
             +scale(test.oxygen)*scale(fw)
             +scale(test.temp)*scale(test.oxygen)*scale(iod)
             +scale(test.oxygen)*scale(iod)
             +scale(test.temp)*scale(iod)
             # +scale(test.temp)*scale(test.oxygen)*scale(ws)
             # +scale(test.oxygen)*scale(ws)
             # +scale(test.temp)*scale(ws)
             # +scale(test.temp)*scale(test.oxygen)*scale(cell.number)
             # +scale(test.oxygen)*scale(cell.number)
             # +scale(test.temp)*scale(cell.number)
             +scale(test.temp)*scale(test.oxygen)*scale(cell.area)
             +scale(test.oxygen)*scale(cell.area)
             +scale(test.temp)*scale(cell.area)
             # +scale(test.temp)*scale(test.oxygen)*scale(genome.pg)
             # +scale(test.oxygen)*scale(genome.pg)
             # +scale(test.temp)*scale(genome.pg)
             ,data=female.hypo.mean,na.action = na.omit,method = "ML")


vif(fhypobg) # all VIF below 5---> OK!!
fhypobg=stepAIC(fhypobg)

# Again, I do end up with identical results.
# -------------------------------------------------------------------------------------
# Lets now plot the results from the most informative models for females and males
# by using the package "visreg"
# -------------------------------------------------------------------------------------
# Females normoxia
f21c <- gls(surv.time ~ test.temp + fw + iod,na.action = na.omit,method="REML",data=female21.mean)
summary(f21c);anova(f21c)

# Females hypoxia
fhypoc<-gls(surv.time~test.temp + iod,data=female.hypo.mean,na.action = na.omit,method = "REML")
summary(fhypoc);anova(fhypoc)

# Males normoxia
m21c <- gls(surv.time ~ test.temp + fw,na.action = na.omit, method="REML",data=male21.mean)
summary(m21c);anova(m21c)

# Males hypoxia
mhypoc<-gls(surv.time~ test.temp*test.oxygen,data=male.hypo.mean,na.action = na.omit,method = "REML")
summary(mhypoc);anova(mhypoc)
#-------------------------------------------------------------------------------
# FIGURE 4
#-------------------------------------------------------------------------------
{
#pdf("Figure 4 Thermal death time curves.pdf",width = 7,height = 7,useDingbats = FALSE)
#png("Figure 4 Thermal death time curves.png",width = 7,height = 7,units = "in",res = 300)
par(mfrow=c(2,2),tcl=-0.4, family="serif",omi=c(0.3,0.3,0,0))

# labels
labs= c("5 min","10 min","30 min","2 h","3 h","6 h")
xs= log10(c(5,10,30,60*2,60*3,60*6))

#Females (fresh mass)
par(mai=c(0.5,0.7,0.3,0))
visreg(f21c,"test.temp",by="fw",overlay =TRUE,band=FALSE,jitter=0.1,partial=FALSE,legend=FALSE,
       ylab="Survival time",cex.lab=1.2, yaxt="n",rug=FALSE,
       line=list(col=c("black"), lwd=2,lty=c(3,2,1)),
       points=list(col=c("white"), pch=21,bg="black",cex=c(0.7,1,1.3)),
       cex.axis=1,xlab="",
       xlim=c(35.6,39.4),ylim=c(0.5,3))
#update axis
axis(2, at=xs, labels=labs, cex.axis=1)

# Add a legend
legend("topleft", legend=c("(A) Females; model 1"), cex=1,bty="n")
legend("topright", legend=c("0.85 mg", "1.2 mg","1.4 mg"),
       lty = c(3,2,1),lwd=1.5,bty="n",cex=0.8)

#Females (iod)
par(mai=c(0.5,0.6,0.3,0.1))
visreg(f21c,"test.temp",by="iod",overlay =TRUE,band=FALSE,jitter=0.1,partial=FALSE,legend=FALSE,
       ylab="",cex.lab=1.2, yaxt="n",rug=FALSE,
       line=list(col=c("black"), lwd=2,lty=c(3,2,1)),
       points=list(col=c("white"), pch=21,bg="black",cex=c(0.7,1,1.3)),
       cex.axis=1,xlab="",
       xlim=c(35.6,39.4),ylim=c(0.5,3))
#update axis
axis(2, at=xs, labels=labs, cex.axis=1)

# Add a legend
legend("topleft", legend=c("(B) Females; model 1"), cex=1,bty="n")
legend("topright", legend=c("454.4 um", "478.7 um","498.5 um"),
       lty = c(3,2,1),lwd=1.5,bty="n",cex=0.8)

#Females (iod under hypoxia)
par(mai=c(0.7,0.7,0.1,0))
visreg(fhypoc,"test.temp",by="iod",overlay =TRUE,band=FALSE,jitter=0.1,partial=FALSE,legend=FALSE,
       ylab="Survival time",cex.lab=1.2, yaxt="n",rug=FALSE,
       line=list(col=c("black"), lwd=2,lty=c(3,2,1)),
       points=list(col=c("white"), pch=21,bg="black",cex=c(0.7,1,1.3)),
       cex.axis=1,xlab="Test temperature (°C)",
       xlim=c(35.6,39.4),ylim=c(0.5,3))
#update axis
axis(2, at=xs, labels=labs, cex.axis=1)
# Add a legend
legend("topleft", legend=c("(C) Females; model 2"), cex=1,bty="n")
legend("topright", legend=c("426.7 um", "483.1 um","520.7 um"),
       lty = c(3,2,1),lwd=1.5,bty="n",cex=0.8)

# Males fresh mass
par(mai=c(0.7,0.7,0.1,0))
#Males (fresh mass)
par(mai=c(0.7,0.6,0,0.1))
visreg(m21c,"test.temp",by="fw",overlay =TRUE,band=FALSE,jitter=0.1,partial=FALSE,legend=FALSE,
       ylab="",cex.lab=1.2, yaxt="n",rug=FALSE,
       line=list(col=c("black"), lwd=2,lty=c(3,2,1)),
       points=list(col=c("white"), pch=21,bg="black",cex=c(0.7,1,1.3)),
       cex.axis=1,xlab="Test temperature (°C)",
       xlim=c(35.6,39.4),ylim=c(0.5,3))
#update axis
axis(2, at=xs, labels=labs, cex.axis=1)
# Add a legend
legend("topleft", legend=c("(D) Males; model 3"), cex=1,bty="n")
legend("topright", legend=c("0.62 mg", "0.78 mg","0.86 mg"),
       lty = c(3,2,1),lwd=1.5,bty="n",cex=0.8)

# close device
#dev.off()
}

#-------------------------------------------------------------------------------
# FIGURE 5
#-------------------------------------------------------------------------------
{
#pdf("Figure 5 Thermal death time curves with at two kPa.pdf",width = 4,height = 4,useDingbats = FALSE)
png("Figure 5 Thermal death time curves with at two kPa.png",width = 4,height = 4,units = "in",res = 300)
par(mfrow=c(1,1),tcl=-0.4, family="serif",
      omi=c(0,0,0,0))
# labels
labs= c("5 min","10 min","30 min","2 h","3 h","6 h")
xs= log10(c(5,10,30,60*2,60*3,60*6))

par(mai=c(0.8,0.8,0.1,0))
visreg(mhypoc,"test.temp",by="test.oxygen",
      band=FALSE,overlay =TRUE,rug=FALSE,legend=FALSE,partial=TRUE,
      line=list(col=c('#B8860B', '#6495ED'),lwd=4),yaxt="n",ylab="Survival time",
      points=list(col=c('#B8860B70', '#6495ED70'),pch=16,cex=1.4),
      xlab="Test temperature (°C)",
      xlim=c(35.6,39.4),ylim=c(0.5,3))

#update axis
axis(2, at=xs, labels=labs, cex.axis=1)
# Add a legend
legend("topright", legend=c("10 kPa", "21 kPa"),cex=1,
       col=c('#B8860B', '#6495ED'),lwd=4,bty="n")
#dev.off()
}
#-----------------------------------------------------------
# Generate data frame with CTmax and z-values from each stock/genotype at 21 kPa for females and males
#-----------------------------------------------------------
get.genotypes <- function(x) unique(all.lines.21$stock)
get.genotypes(all.lines.21)
genotypes <- dlply(all.lines.21, .(sex), function(x) unique(x$stock))
model <- function(x){
  lm(surv.time ~ test.temp, data=x)
}
fitted.linear.model <- dlply(all.lines.21, .(stock, sex), model)
coef(fitted.linear.model[[1]])
ldply(fitted.linear.model, coef)
ldply(fitted.linear.model, function(x) summary(x)$r.squared)
model <- function(x){
  fit <- lm(surv.time ~ test.temp, data=x)
  data.frame(n=length(x$test.temp), 
             r2=summary(fit)$r.squared, 
             a=coef(fit)[[1]], 
             b=coef(fit)[[2]])
}
TDT.21<-ddply(all.lines.21, .(stock,sex), model)
TDT.21$ctmax<--1*(TDT.21$a/TDT.21$b)#CTmax
TDT.21$z.value<-(-1/TDT.21$b)#z-value
TDT.21$Q10<-((10)^(10/TDT.21$z.value))#Q10 as in Castañeda et al 2015

#round data
round_df <- function(TDT.21, digits) {
  nums <- vapply(TDT.21, is.numeric, FUN.VALUE = logical(1))
  TDT.21[,nums] <- round(TDT.21[,nums], digits = digits)
  
  (TDT.21)
}

TDT.21<-round_df(TDT.21, digits=2)

# Export data frame of TDT parameters time at 21 kPa for females and males
write.csv(TDT.21,"TDT parameters at 21 kPa for each sex.csv",row.names = FALSE)
#-----------------------------------------------------------
# Generate data frame with CTmax and z-values from each stock/genotype at two 
# oxygen levels for females
#-----------------------------------------------------------
get.genotypes <- function(x) unique(female.hypo$stock)
get.genotypes(female.hypo)
genotypes <- dlply(female.hypo, .(test.oxygen), function(x) unique(x$stock))
model <- function(x){
  lm(surv.time ~ test.temp, data=x)
}
fitted.linear.model <- dlply(female.hypo, .(stock, test.oxygen), model)
coef(fitted.linear.model[[1]])
ldply(fitted.linear.model, coef)
ldply(fitted.linear.model, function(x) summary(x)$r.squared)
model <- function(x){
  fit <- lm(surv.time ~ test.temp, data=x)
  data.frame(n=length(x$test.temp), 
             r2=summary(fit)$r.squared, 
             a=coef(fit)[[1]], 
             b=coef(fit)[[2]])
}
TDT.hypo.f<-ddply(female.hypo, .(stock,test.oxygen), model)
TDT.hypo.f$ctmax<--1*(TDT.hypo.f$a/TDT.hypo.f$b)#CTmax
TDT.hypo.f$z.value<-(-1/TDT.hypo.f$b)#z-value
TDT.hypo.f$Q10<-((10)^(10/TDT.hypo.f$z.value))#Q10 as in Castañeda et al 2015
TDT.hypo.f$sex<-"female"

#round data
round_df <- function(TDT.hypo.f, digits) {
  nums <- vapply(TDT.hypo.f, is.numeric, FUN.VALUE = logical(1))
  TDT.hypo.f[,nums] <- round(TDT.hypo.f[,nums], digits = digits)
  
  (TDT.hypo.f)
}

TDT.hypo.f<-round_df(TDT.hypo.f, digits=2)

#-----------------------------------------------------------
# Generate data frame with CTmax and z-values from each stock/genotype at two 
# oxygen levels for males
#-----------------------------------------------------------
get.genotypes <- function(x) unique(male.hypo$stock)
get.genotypes(male.hypo)
genotypes <- dlply(male.hypo, .(test.oxygen), function(x) unique(x$stock))
model <- function(x){
  lm(surv.time ~ test.temp, data=x)
}
fitted.linear.model <- dlply(male.hypo, .(stock, test.oxygen), model)
coef(fitted.linear.model[[1]])
ldply(fitted.linear.model, coef)
ldply(fitted.linear.model, function(x) summary(x)$r.squared)
model <- function(x){
  fit <- lm(surv.time ~ test.temp, data=x)
  data.frame(n=length(x$test.temp), 
             r2=summary(fit)$r.squared, 
             a=coef(fit)[[1]], #intercept
             b=coef(fit)[[2]]) #slope
}
TDT.hypo.m<-ddply(male.hypo, .(stock,test.oxygen), model)
TDT.hypo.m$ctmax<--1*(TDT.hypo.m$a/TDT.hypo.m$b)#CTmax
TDT.hypo.m$z.value<-(-1/TDT.hypo.m$b)#z-value
TDT.hypo.m$Q10<-((10)^(10/TDT.hypo.m$z.value))#Q10 as in Castañeda et al 2015
TDT.hypo.m$sex<-"male"

#round data
round_df <- function(TDT.hypo.m, digits) {
  nums <- vapply(TDT.hypo.m, is.numeric, FUN.VALUE = logical(1))
  TDT.hypo.m[,nums] <- round(TDT.hypo.m[,nums], digits = digits)
  
  (TDT.hypo.m)
}

TDT.hypo.m<-round_df(TDT.hypo.m, digits=2)
TDT.hypo.m
#merge females and males
TDT.FULL<-rbind(TDT.hypo.f,TDT.hypo.m)

# Export data frame of TDT parameters time at two kPa and for females and males
write.csv(TDT.FULL,"TDT parameters at two kPa for females and males.csv",row.names = FALSE)
# -------------------------------------------------------------------------------------
# Given we have specific predictions for the effects of cell size and body mass, now we 
# will estimate the weight of evidence both for models with fresh mass, cell area and their interaction 
# with test temperature and oxygen.
# 
# Females at 21kPa
f0<-gls(surv.time~1,na.action = na.omit,method="ML",data=female21.mean)
summary(f0)

f1<-gls(surv.time~test.temp,na.action = na.omit,method="ML",data=female21.mean)
summary(f1)

f2<-gls(surv.time~test.temp * cell.area,na.action = na.omit,method="ML",data=female21.mean)
summary(f2)

f3<-gls(surv.time~test.temp * fw,na.action = na.omit,method="ML",data=female21.mean)
summary(f3);anova(f3)

f4<-gls(surv.time~test.temp + cell.area,na.action = na.omit,method="ML",data=female21.mean)
summary(f4)

f5<-gls(surv.time~test.temp + fw,na.action = na.omit,method="ML",data=female21.mean)
summary(f5);anova(f5)
f.list.21 <- list(f0,f1,f2,f3,f4,f5)

f.names.21 <-c("Null",
                 "Stress temp",
                 "Stress temp * cell area",
                 "Stress temp * fresh mass",
                 "Stress temp + cell area",
                 "Stress temp + fresh mass")

#compare by using AICc
f.21<-aictab(f.list.21,f.names.21, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
f.21

# Model selection based on AICc:
#   
#                          K   AICc Delta_AICc AICcWt Cum.Wt     LL
# Stress temp + fresh mass 4 -83.93       0.00   0.45   0.45  46.24
# Stress temp * fresh mass 5 -83.51       0.42   0.37   0.82  47.17
# Stress temp              3 -81.29       2.64   0.12   0.94  43.81
# Stress temp + cell area  4 -79.21       4.72   0.04   0.99  43.88
# Stress temp * cell area  5 -76.94       6.99   0.01   1.00  43.89
# Null                     2  98.65     182.58   0.00   1.00 -47.24

#Table 2 Females
write.csv(f.21,"Model selection for females at 21 kPa.csv",row.names = FALSE)

# Males at 21kPa
m0<-gls(surv.time~1,na.action = na.omit,method="ML",data=male21.mean)
summary(m0)

m1<-gls(surv.time~test.temp,na.action = na.omit,method="ML",data=male21.mean)
summary(m1)

m2<-gls(surv.time~test.temp * cell.area,na.action = na.omit,method="ML",data=male21.mean)
summary(m2)

m3<-gls(surv.time~test.temp * fw,na.action = na.omit,method="ML",data=male21.mean)
summary(m3)

m4<-gls(surv.time~test.temp + cell.area,na.action = na.omit,method="ML",data=male21.mean)
summary(m4)

m5<-gls(surv.time~test.temp + fw,na.action = na.omit,method="ML",data=male21.mean)
summary(m5);anova(m5)

m.list.21 <- list(m0,m1,m2,m3,m4,m5)

m.names.21 <-c("Null",
               "Stress temp",
               "Stress temp * cell area",
               "Stress temp * fresh mass",
               "Stress temp + cell area",
               "Stress temp + fresh mass")

#compare by using AICc
m.21<-aictab(m.list.21,m.names.21, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
m.21

# Model selection based on AICc:
# 
#                          K   AICc Delta_AICc AICcWt Cum.Wt     LL
# Stress temp + fresh mass 4 -88.46       0.00   0.62   0.62  48.49
# Stress temp * fresh mass 5 -86.33       2.12   0.21   0.83  48.57
# Stress temp              3 -84.35       4.10   0.08   0.91  45.33
# Stress temp * cell area  5 -83.24       5.21   0.05   0.96  47.03
# Stress temp + cell area  4 -83.00       5.45   0.04   1.00  45.77
# Null                     2  67.54     155.99   0.00   1.00 -31.69

# Table 2 males
write.csv(m.21,"Model selection for males at 21 kPa.csv",row.names = FALSE)

# Females at two kPa
#
fh0<-gls(surv.time~1,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh0)

fh1<-gls(surv.time~test.temp,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh1);anova(fh1)

fh2<-gls(surv.time~test.temp * cell.area,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh2)

fh3<-gls(surv.time~test.temp * fw,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh3)

fh4<-gls(surv.time~test.temp + cell.area,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh4)

fh5<-gls(surv.time~test.temp + fw,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh5)

fh6<-gls(surv.time~test.temp * cell.area * test.oxygen,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh6)

fh7<-gls(surv.time~test.temp * fw * test.oxygen,na.action = na.omit,method="ML",data=female.hypo.mean)
summary(fh7)


f.list.hypo <- list(fh0,fh1,fh2,fh3,fh4,fh5,fh6,fh7)

f.names.hypo <-c("Null",
               "Stress temp",
               "Stress temp * cell area",
               "Stress temp * fresh mass",
               "Stress temp + cell area",
               "Stress temp + fresh mass",
               "Stress temp * cell area * oxygen",
               "Stress temp * fresh mass * oxygen")

#compare by using AICc
f.hypo<-aictab(f.list.hypo,f.names.hypo, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
f.hypo

# Model selection based on AICc:
#   
#                                   K   AICc Delta_AICc AICcWt Cum.Wt     LL
# Stress temp                       3 -59.43       0.00   0.51   0.51  32.99
# Stress temp + fresh mass          4 -57.27       2.17   0.17   0.68  33.10
# Stress temp + cell area           4 -57.15       2.28   0.16   0.84  33.04
# Stress temp * cell area           5 -55.91       3.52   0.09   0.93  33.67
# Stress temp * fresh mass          5 -55.49       3.94   0.07   1.00  33.46
# Stress temp * cell area * oxygen  9 -44.61      14.83   0.00   1.00  33.67
# Stress temp * fresh mass * oxygen 9 -44.19      15.25   0.00   1.00  33.46
# Null                              2  67.24     126.67   0.00   1.00 -31.49

write.csv(f.hypo,"Model selection for females at two kPa.csv",row.names = FALSE)

# Males at two kPa
#
mh0<-gls(surv.time~1,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh0)

mh1<-gls(surv.time~test.temp,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh1)

mh2<-gls(surv.time~test.temp * cell.area,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh2)

mh3<-gls(surv.time~test.temp * fw,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh3)

mh4<-gls(surv.time~test.temp + cell.area,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh4)

mh5<-gls(surv.time~test.temp + fw,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh5)

mh6<-gls(surv.time~test.temp * cell.area * test.oxygen,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh6);anova(mh6)

mh7<-gls(surv.time~test.temp * fw * test.oxygen,na.action = na.omit,method="ML",data=male.hypo.mean)
summary(mh7);anova(mh7)


m.list.hypo <- list(mh0,mh1,mh2,mh3,mh4,mh5,mh6,mh7)

m.names.hypo <-c("Null",
                 "Stress temp",
                 "Stress temp * cell area",
                 "Stress temp * fresh mass",
                 "Stress temp + cell area",
                 "Stress temp + fresh mass",
                 "Stress temp * cell area * oxygen",
                 "Stress temp * fresh mass * oxygen")

#compare by using AICc
m.hypo<-aictab(m.list.hypo,m.names.hypo, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
m.hypo

# Model selection based on AICc:
#   
#                                   K   AICc Delta_AICc AICcWt Cum.Wt     LL
# Stress temp * fresh mass * oxygen 9 -46.43       0.00   0.55   0.55  34.72
# Stress temp * cell area * oxygen  9 -45.86       0.57   0.42   0.97  34.43
# Stress temp                       3 -38.73       7.70   0.01   0.98  22.65
# Stress temp * fresh mass          5 -37.60       8.83   0.01   0.99  24.55
# Stress temp + cell area           4 -36.66       9.78   0.00   0.99  22.82
# Stress temp * cell area           5 -36.51       9.92   0.00   1.00  24.01
# Stress temp + fresh mass          4 -36.33      10.10   0.00   1.00  22.65
# Null                              2  39.28      85.71   0.00   1.00 -17.50

write.csv(m.hypo,"Model selection for males at two kPa.csv",row.names = FALSE)
#####################################################################################
##################################END OF SCRIPT######################################
#####################################################################################