# -------------------------------------------------------------------------------------
# Script to analyse the effect of body size-related traits on survival time of 
# DGRP lines
# Data generated by Felix P Leiva, Radboud University
# Citation: 
# Created by Felix P Leiva
# -------------------------------------------------------------------------------------
# Cleaning working space and setting date
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# -------------------------------------------------------------------------------------
setwd("C:/Users/Invunche/Dropbox/Radboud University/publicaciones/Thesis/3. Thermal tolerance on big and small cells/manuscritos/Submission FE")
# check directory
getwd()
# -------------------------------------------------------------------------------------
#Libraries
library(lme4)
library(nlme)
library(car)
library(ggplot2)
library(dplyr)
library(tidyr)
library(plyr)
library(MASS)
library(cowplot)
# ------------------------------------------------------------------------------
#Load data of normoxia (20 lines)
all.lines.21<-read.csv("Survival time of Drosophila melanogaster and its associated size traits at 21 kPa.csv")

#Load data of hypoxia (6 lines)
all.lines.hypo<-read.csv("Survival time of Drosophila melanogaster and its associated size traits at two oxygen levels.csv")

# subset by sex
data_f<-subset(all.lines.21,sex!="male") #females
data_m<-subset(all.lines.21,sex=="male") #males
data_f_hypo<-subset(all.lines.hypo,sex!="male") #females
data_m_hypo<-subset(all.lines.hypo,sex=="male") #males
# ------------------------------------------------------------------------------
# Modelling the TDT curves by genotype under normoxia
# ------------------------------------------------------------------------------
# mixed model with random variation in intercept and slope
f1<-lmer(surv.time ~ test.temp + (1+test.temp|stock), REML = TRUE, data=data_f)
summary(f1)

# mixed model with random variation in intercept
f2<-lmer(surv.time ~ test.temp + (1|stock), REML = TRUE, data=data_f)
summary(f2)


#Comparing the models using AIC and BIC:
AIC(f1,f2)
BIC(f1,f2)
#comparing using Anova
anova(f1,f2)
#Model f1 (variation in intercept and slopes between stock) 
#is a better fit both in AIC and BIC

#PLOT
coef(summary(f1))[ , "Estimate"]
# (Intercept)   test.temp 
# 15.5539523  -0.3714353 

data_f$pred <- predict(f1,re.form=NA)
data_f$pred1 <- predict(f1)
f1 <- ggplot(data_f,aes(test.temp,surv.time))+
  ylim(c(0,3))+xlim(c(35.5,39.5))+
  geom_jitter(position=position_jitter(0.1),size=2,colour="grey",shape=21)
f1.plot=
  f1 +   geom_line(colour="gray",aes(y=pred1,group=stock)) +
  geom_line(colour="#4DAC26",lwd=2,aes(y=pred,group=stock))+
  xlab("Test temperature (°C)") + 
  ylab("Survival time, minutes") + 
  ggtitle("Females tested under normoxia")+
  theme(plot.title = element_text(hjust = 0.5,size = 20,face = "bold"))+
  theme_bw()
f1.plot

#Males
m1<-lmer(surv.time ~ test.temp + (1+test.temp|stock), REML = TRUE, data=data_m)
summary(m1)

# mixed model with random variation in intercept
m2<-lmer(surv.time ~ test.temp + (1|stock), REML = TRUE, data=data_m)
summary(m2)

#Comparing the models using AIC and BIC:
AIC(m1,m2)
BIC(m1,m2)
#comparing using Anova
anova(m1,m2)
#Model m1 (variation in intercept and slopes between stock) 
#is a better fit both in AIC and BIC

#PLOT
coef(summary(m1))[ , "Estimate"]
# (Intercept)   test.temp 
# 12.9248906  -0.3021364 

data_m$pred <- predict(m1,re.form=NA)
data_m$pred1 <- predict(m1)
m1 <- ggplot(data_m,aes(test.temp,surv.time))+
  ylim(c(0,3))+xlim(c(35.5,39.5))+
  geom_jitter(position=position_jitter(0.1),size=2,colour="grey",shape=21)
m1.plot=
  m1 +   geom_line(colour="gray",aes(y=pred1,group=stock)) +
  geom_line(colour="#A6761D",lwd=2,aes(y=pred,group=stock))+
  xlab("Test temperature (°C)") + 
  ylab("Survival time, minutes") + 
  ggtitle("Males tested under normoxia")+
  theme(plot.title = element_text(hjust = 0.5,size = 20,face = "bold"))+
  theme_bw()
m1.plot

#Figure S6
Figure_S6<-plot_grid(f1.plot,m1.plot,
                     labels=c("A","B"),
                     nrow = 1,ncol = 2,label_size=15)

#Store Plots
ggsave('Figure S6.pdf',Figure_S6,width=12,height=6)
ggsave('Figure S6.png',Figure_S6,width=12,height=6)
