# -------------------------------------------------------------------------------------
# Script to test and plot effects of sex, body mass, cell area and oxygen
# on CTmax and z-value
# Data generated by Félix P Leiva, Radboud University
# Created by Félix P Leiva on 20201203 (YYYYMMDD)
# # -------------------------------------------------------------------------------------
# Clean working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# -------------------------------------------------------------------------------------
#Set directory
setwd("C:/Users/Invunche/Dropbox/Radboud University/publicaciones/Thesis/3. Thermal tolerance on big and small cells/manuscritos/Submission FE")
getwd()# check directory
# -------------------------------------------------------------------------------------
#Libraries
#
library(AICcmodavg)
# -------------------------------------------------------------------------------------
# load data
traits<-read.csv("Phenotypic traits data of DGRP lines.csv")
head(traits)
str(traits)
traits$stock<-as.factor(traits$stock)
#reorder the columns
traits<-traits[,c(1:6,8,9,7,11,10)]
names(traits)
traits.mean<-aggregate(cbind(fw,iod,ws,cell.number,cell.area)~stock+genotype+sex,traits,mean)

# TDT for 20 lines
tdt.n<-read.csv("TDT parameters at 21 kPa for each sex.csv")

# TDT for 6 lines
tdt.h<-read.csv("TDT parameters at two kPa for females and males.csv")
# -------------------------------------------------------------------------------------
# Add trait data to TDT parameters and subset by sex
# -------------------------------------------------------------------------------------
#normoxia
tdt.n<-merge(tdt.n,traits.mean,by=c("stock","sex")) #20 DGRP lines, normoxia
tdt.h<-merge(tdt.h,traits.mean,by=c("stock","sex")) #6 DGRP lines,hypoxia

#subset by sex under normoxic conditions
male.n<-subset(tdt.n,tdt.n$sex=="male")
female.n<-subset(tdt.n,tdt.n$sex!="male")

#subset by sex for two oxygen conditions
male.h<-subset(tdt.h,tdt.h$sex=="male")
female.h<-subset(tdt.h,tdt.h$sex!="male")

# -------------------------------------------------------------------------------------
# Formal test (MANOVAs) for normoxic conditions sex pooled
# -------------------------------------------------------------------------------------
outcome <- cbind(tdt.n$ctmax, tdt.n$z.value)
lm.man<-manova(outcome~sex*cell.area+sex*fw,data=tdt.n)
summary(lm.man,test="Wilks")

#              Df   Wilks approx F num Df den Df  Pr(>F)  
# sex            1 0.78110   4.6240      2     33 0.01697 *
# cell.area      1 0.96965   0.5165      2     33 0.60136  
# fw             1 0.83363   3.2931      2     33 0.04966 *
# sex:cell.area  1 0.97331   0.4525      2     33 0.63991  
# sex:fw         1 0.96163   0.6584      2     33 0.52433  
# Residuals     34                                         

# -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for CTmax (normoxic conditions) sex pooled
# -------------------------------------------------------------------------------------
lm.anov.ctmax<-lm(ctmax~sex*cell.area+sex*fw,data=tdt.n)

summary(lm.anov.ctmax)

# Coefficients:
#                    Estimate Std. Error t value Pr(>|t|)    
# (Intercept)       41.749032   3.852758  10.836 1.43e-12 ***
# sexmale           -4.011671   5.458360  -0.735    0.467    
# cell.area          0.007757   0.025266   0.307    0.761    
# fw                -0.889417   1.950053  -0.456    0.651    
# sexmale:cell.area  0.020643   0.040637   0.508    0.615    
# sexmale:fw         2.670359   4.298581   0.621    0.539

anova(lm.anov.ctmax)
#               Df Sum Sq Mean Sq F value  Pr(>F)  
# sex            1 14.400 14.4000  7.1296 0.01154 *
# cell.area      1  1.982  1.9820  0.9813 0.32888  
# fw             1  0.119  0.1189  0.0589 0.80973  
# sex:cell.area  1  1.837  1.8372  0.9096 0.34695  
# sex:fw         1  0.779  0.7794  0.3859 0.53860  
# Residuals     34 68.671  2.0197

# -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for z-value (normoxic conditions) sex pooled
# -------------------------------------------------------------------------------------
lm.anov.z<-lm(z.value~sex*cell.area+sex*fw,data=tdt.n)

summary(lm.anov.z)
# Coefficients:
#                    Estimate Std. Error t value Pr(>|t|)
# (Intercept)        2.807247   2.354150   1.192    0.241
# sexmale           -2.342917   3.335221  -0.702    0.487
# cell.area          0.006451   0.015438   0.418    0.679
# fw                -0.951386   1.191541  -0.798    0.430
# sexmale:cell.area  0.014106   0.024830   0.568    0.574
# sexmale:fw         1.117229   2.626561   0.425    0.673

anova(lm.anov.z)

# Response: z.value
#               Df  Sum Sq Mean Sq F value  Pr(>F)   
# sex            1  6.4000  6.4000  8.4871 0.00628 **
# cell.area      1  0.6369  0.6369  0.8445 0.36458   
# fw             1  0.3962  0.3962  0.5254 0.47349   
# sex:cell.area  1  0.6223  0.6223  0.8253 0.37003   
# sex:fw         1  0.1364  0.1364  0.1809 0.67326   
# Residuals     34 25.6389  0.7541

# -------------------------------------------------------------------------------------
# Formal test (MANOVA)for normoxic conditions for females
# -------------------------------------------------------------------------------------
outcome <- cbind(female.n$ctmax, female.n$z.value)
lm.man.fem<-manova(outcome~cell.area+fw,data=female.n)

summary(lm.man.fem,test="Wilks")
#           Df   Wilks approx F num Df den Df  Pr(>F)  
# cell.area  1 0.99581   0.0337      2     16 0.96696  
# fw         1 0.58281   5.7266      2     16 0.01331 *
# Residuals 17                                      

# -------------------------------------------------------------------------------------
# Formal test (ANOVA) for CTmax (normoxic conditions) for females
# -------------------------------------------------------------------------------------
lm.anov.ctmax<-lm(ctmax~cell.area+fw,data=female.n)
summary(lm.anov.ctmax)
# Coefficients:
#              Estimate Std. Error t value Pr(>|t|)    
# (Intercept) 41.749032   2.166415  19.271 5.49e-13 ***
# cell.area    0.007757   0.014207   0.546    0.592    
# fw          -0.889417   1.096520  -0.811    0.429

anova(lm.anov.ctmax)
# Response: ctmax
#           Df  Sum Sq Mean Sq F value Pr(>F)
# cell.area  1  0.0305 0.03047  0.0477 0.8297
# fw         1  0.4202 0.42016  0.6579 0.4285
# Residuals 17 10.8564 0.63861
# -------------------------------------------------------------------------------------
# Formal test (ANOVA) for z (normoxic conditions) for females
# -------------------------------------------------------------------------------------
lm.anov.z<-lm(z.value~cell.area+fw,data=female.n)
summary(lm.anov.z)
# Coefficients:
#              Estimate Std. Error t value Pr(>|t|)  
# (Intercept)  2.807247   1.134365   2.475   0.0242 *
# cell.area    0.006451   0.007439   0.867   0.3979  
# fw          -0.951386   0.574153  -1.657   0.1159

anova(lm.anov.z)

# Response: z.value
#           Df  Sum Sq Mean Sq F value Pr(>F)
# cell.area  1 0.00514 0.00514  0.0294 0.8660
# fw         1 0.48075 0.48075  2.7457 0.1159
# Residuals 17 2.97651 0.17509
# 

# -------------------------------------------------------------------------------------
# Formal test (MANOVA) for normoxic conditions for males
# -------------------------------------------------------------------------------------
outcome <- cbind(male.n$ctmax, male.n$z.value)
lm.man.mal<-manova(outcome~cell.area+fw,data=male.n)

summary(lm.man.mal,test="Wilks")
#           Df  Wilks approx F num Df den Df Pr(>F)
# cell.area  1 0.9310  0.59289      2     16 0.5644
# fw         1 0.8257  1.68873      2     16 0.2161
# Residuals 17                                      

# -------------------------------------------------------------------------------------
# Formal test (ANOVA) for CTmax (normoxic conditions) for males
# -------------------------------------------------------------------------------------
lm.anov.ctmax<-lm(ctmax~cell.area+fw,data=male.n)
summary(lm.anov.ctmax)
# Coefficients:
#              Estimate Std. Error t value Pr(>|t|)    
# (Intercept)  37.7374     5.0173   7.521 8.36e-07 ***
# cell.area     0.0284     0.0413   0.688    0.501    
# fw            1.7809     4.9709   0.358    0.725

anova(lm.anov.ctmax)
# Response: ctmax
#           Df Sum Sq Mean Sq F value Pr(>F)
# cell.area  1  3.830  3.8304  1.1263 0.3034
# fw         1  0.437  0.4365  0.1284 0.7246
# Residuals 17 57.815  3.4009
# -------------------------------------------------------------------------------------
# Formal test (ANOVA) for z (normoxic conditions) for males
# -------------------------------------------------------------------------------------
lm.anov.z<-lm(z.value~cell.area+fw,data=male.n)
summary(lm.anov.z)
# Coefficients:
#              Estimate Std. Error t value Pr(>|t|)
# (Intercept)  0.46433    3.14124   0.148    0.884
# cell.area    0.02056    0.02586   0.795    0.438
# fw           0.16584    3.11222   0.053    0.958

anova(lm.anov.z)

# Response: z.value
#           Df  Sum Sq Mean Sq F value Pr(>F)
# cell.area  1  1.3022 1.30218  0.9768 0.3368
# fw         1  0.0038 0.00379  0.0028 0.9581
# Residuals 17 22.6624 1.33308
# 
# -------------------------------------------------------------------------------------
# Formal test (MANOVA) for hypoxic conditions sex pooled
# -------------------------------------------------------------------------------------
outcome <- cbind(tdt.h$ctmax, tdt.h$z.value)
lm.man.hyp<-manova(outcome~sex*cell.area+sex*fw+test.oxygen*cell.area+test.oxygen*fw+
               test.oxygen*sex,data=tdt.h)

summary(lm.man.hyp,test="Wilks")
#                       Df   Wilks approx F num Df den Df    Pr(>F)    
# sex                    1 0.62903   3.8333      2     13 0.04913 *
# cell.area              1 0.66995   3.2022      2     13 0.07401 .
# fw                     1 0.94642   0.3680      2     13 0.69911  
# test.oxygen            1 0.50516   6.3671      2     13 0.01181 *
# sex:cell.area          1 0.95300   0.3205      2     13 0.73134  
# sex:fw                 1 0.89326   0.7767      2     13 0.48013  
# cell.area:test.oxygen  1 0.86662   1.0004      2     13 0.39435  
# fw:test.oxygen         1 0.65079   3.4878      2     13 0.06129 .
# sex:test.oxygen        1 0.90230   0.7038      2     13 0.51261  
# Residuals             14
# 
# -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for CTmax (hypoxic conditions) TABLE 2 sex pooled
# -------------------------------------------------------------------------------------
hyp.anov.ctmax<-lm(ctmax~sex*cell.area+sex*fw+test.oxygen*cell.area+test.oxygen*fw+
                      test.oxygen*sex,data=tdt.h)

summary(hyp.anov.ctmax)
# Coefficients:
#                       Estimate Std. Error t value Pr(>|t|)    
# (Intercept)           39.144316   7.901727   4.954 0.000212 ***
# sexmale               -1.700383   5.379495  -0.316 0.756601    
# cell.area              0.039783   0.044815   0.888 0.389683    
# fw                    -1.508956   7.202234  -0.210 0.837066    
# test.oxygen           -0.085305   0.463312  -0.184 0.856560    
# sexmale:cell.area     -0.036053   0.040680  -0.886 0.390441    
# sexmale:fw            10.949401   8.477821   1.292 0.217435    
# cell.area:test.oxygen -0.001327   0.002644  -0.502 0.623519    
# fw:test.oxygen         0.158812   0.435403   0.365 0.720751    
# sexmale:test.oxygen    0.013201   0.194747   0.068 0.946916 

anova(hyp.anov.ctmax)

# Response: ctmax
# Df  Sum Sq Mean Sq F value   Pr(>F)   
# sex                    1  4.9232  4.9232  4.1174 0.061903 . 
# cell.area              1  5.9149  5.9149  4.9468 0.043102 * 
# fw                     1  0.8090  0.8090  0.6766 0.424562   
# test.oxygen            1 11.4678 11.4678  9.5909 0.007881 **
# sex:cell.area          1  0.0967  0.0967  0.0809 0.780276   
# sex:fw                 1  1.9945  1.9945  1.6681 0.217435   
# cell.area:test.oxygen  1  0.0121  0.0121  0.0102 0.921163   
# fw:test.oxygen         1  0.4608  0.4608  0.3854 0.544720   
# sex:test.oxygen        1  0.0055  0.0055  0.0046 0.946916   
# Residuals             14 16.7399  1.1957

# -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for z (hypoxic conditions) sex pooled
# -------------------------------------------------------------------------------------
hyp.anov.z<-lm(z.value~sex*cell.area+sex*fw+test.oxygen*cell.area+test.oxygen*fw+
                      test.oxygen*sex,data=tdt.h)

summary(hyp.anov.z)

#                       Estimate Std. Error t value Pr(>|t|)
# (Intercept)           -0.961727   5.034220  -0.191    0.851
# sexmale               -0.844724   3.427296  -0.246    0.809
# cell.area              0.039507   0.028552   1.384    0.188
# fw                    -1.297051   4.588570  -0.283    0.782
# test.oxygen            0.071425   0.295178   0.242    0.812
# sexmale:cell.area     -0.020296   0.025917  -0.783    0.447
# sexmale:fw             6.899119   5.401252   1.277    0.222
# cell.area:test.oxygen -0.001679   0.001685  -0.997    0.336
# fw:test.oxygen         0.113203   0.277397   0.408    0.689
# sexmale:test.oxygen   -0.023837   0.124074  -0.192    0.850

anova(hyp.anov.z)

#                       Df Sum Sq Mean Sq F value  Pr(>F)   
# sex                    1 2.8222  2.8222  5.8149 0.03020 * 
# cell.area              1 2.9562  2.9562  6.0910 0.02709 * 
# fw                     1 0.2605  0.2605  0.5367 0.47591   
# test.oxygen            1 5.7918  5.7918 11.9336 0.00387 **
# sex:cell.area          1 0.0949  0.0949  0.1955 0.66515   
# sex:fw                 1 0.7918  0.7918  1.6315 0.22227   
# cell.area:test.oxygen  1 0.0801  0.0801  0.1651 0.69065   
# fw:test.oxygen         1 0.6621  0.6621  1.3643 0.26231   
# sex:test.oxygen        1 0.0179  0.0179  0.0369 0.85041   
# Residuals             14 6.7947  0.4853

# -------------------------------------------------------------------------------------
# Formal test (MANOVA) for hypoxic conditions females
# -------------------------------------------------------------------------------------
outcome <- cbind(female.h$ctmax, female.h$z.value)
hyp.man.fem<-manova(outcome~cell.area*test.oxygen+fw*test.oxygen,
                    data=female.h)

summary(hyp.man.fem,test="Wilks")

#                       Df   Wilks approx F num Df den Df  Pr(>F)  
# cell.area              1 0.45047   3.0497      2      5 0.13620  
# test.oxygen            1 0.35834   4.4767      2      5 0.07687 .
# fw                     1 0.96516   0.0902      2      5 0.91517  
# cell.area:test.oxygen  1 0.53085   2.2094      2      5 0.20532  
# test.oxygen:fw         1 0.83220   0.5041      2      5 0.63178  
# Residuals              6 

# -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for CTmax (hypoxic conditions) females
# -------------------------------------------------------------------------------------
hyp.ctmax.fem<-lm(ctmax~cell.area*test.oxygen+fw*test.oxygen,
                    data=female.h)

summary(hyp.ctmax.fem)
# Coefficients:
# Estimate Std. Error t value Pr(>|t|)   
# (Intercept)           36.828678   8.643953   4.261  0.00532 **
# cell.area              0.043530   0.047545   0.916  0.39521   
# test.oxygen            0.064091   0.525568   0.122  0.90692   
# fw                    -0.169591   6.595850  -0.026  0.98032   
# cell.area:test.oxygen -0.001569   0.002891  -0.543  0.60690   
# test.oxygen:fw         0.072401   0.401039   0.181  0.86268

anova(hyp.ctmax.fem)
# Response: ctmax
#                       Df Sum Sq Mean Sq F value  Pr(>F)  
# cell.area              1 2.2485  2.2485  2.4454 0.16890  
# test.oxygen            1 4.4287  4.4287  4.8164 0.07062 .
# fw                     1 0.1715  0.1715  0.1865 0.68091  
# cell.area:test.oxygen  1 0.2451  0.2451  0.2665 0.62413  
# test.oxygen:fw         1 0.0300  0.0300  0.0326 0.86268  
# Residuals              6 5.5170  0.9195
# 
## -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for CTmax (hypoxic conditions) females
# -------------------------------------------------------------------------------------
hyp.z.fem<-lm(z.value~cell.area*test.oxygen+fw*test.oxygen,
                  data=female.h)

summary(hyp.z.fem)
# Coefficients:
#                          Estimate Std. Error t value Pr(>|t|)
# (Intercept)           -1.270826   4.607529  -0.276    0.792
# cell.area              0.037928   0.025343   1.497    0.185
# test.oxygen            0.091367   0.280146   0.326    0.755
# fw                    -0.838169   3.515818  -0.238    0.820
# cell.area:test.oxygen -0.001578   0.001541  -1.024    0.345
# test.oxygen:fw         0.083598   0.213768   0.391    0.709

anova(hyp.z.fem)
# Response: z.value
#                       Df  Sum Sq Mean Sq F value  Pr(>F)  
# cell.area              1 1.01248 1.01248  3.8755 0.09653 .
# test.oxygen            1 1.80963 1.80963  6.9268 0.03896 *
# fw                     1 0.03957 0.03957  0.1515 0.71056  
# cell.area:test.oxygen  1 0.23524 0.23524  0.9004 0.37930  
# test.oxygen:fw         1 0.03995 0.03995  0.1529 0.70926  
# Residuals              6 1.56751 0.26125


# -------------------------------------------------------------------------------------
# Formal test (MANOVA) for hypoxic conditions males 
# -------------------------------------------------------------------------------------
outcome <- cbind(male.h$ctmax, male.h$z.value)
hyp.man.mal<-manova(outcome~cell.area*test.oxygen+fw*test.oxygen,
                    data=male.h)

summary(hyp.man.mal,test="Wilks")

#                       Df   Wilks approx F num Df den Df  Pr(>F)  
# cell.area              1 0.68507   1.1493      2      5 0.38845  
# test.oxygen            1 0.45367   3.0106      2      5 0.13863  
# fw                     1 0.71981   0.9732      2      5 0.43958  
# cell.area:test.oxygen  1 0.33758   4.9056      2      5 0.06621 .
# test.oxygen:fw         1 0.70868   1.0277      2      5 0.42279  
# Residuals              6

# -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for CTmax (hypoxic conditions) males
# -------------------------------------------------------------------------------------
hyp.ctmax.mal<-lm(ctmax~cell.area*test.oxygen+fw*test.oxygen,
                  data=male.h)

summary(hyp.ctmax.mal)
# Coefficients:
#                        Estimate Std. Error t value Pr(>|t|)   
# (Intercept)           41.246552  10.959233   3.764  0.00936 **
# cell.area              0.043903   0.133316   0.329  0.75311   
# test.oxygen           -0.317434   0.666341  -0.476  0.65065   
# fw                    -2.902415  29.639203  -0.098  0.92518   
# cell.area:test.oxygen -0.003919   0.008106  -0.483  0.64590   
# test.oxygen:fw         0.955125   1.802117   0.530  0.61514

anova(hyp.ctmax.mal)
Response: ctmax
#                       Df  Sum Sq Mean Sq F value  Pr(>F)  
# cell.area              1  3.8109  3.8109  2.1265 0.19504  
# test.oxygen            1  7.2075  7.2075  4.0218 0.09173 .
# fw                     1  2.5841  2.5841  1.4420 0.27507  
# cell.area:test.oxygen  1  0.0019  0.0019  0.0011 0.97512  
# test.oxygen:fw         1  0.5034  0.5034  0.2809 0.61514  
# Residuals              6 10.7526  1.7921
# 
## -------------------------------------------------------------------------------------
# Formal test (ANOVAs) for z-value (hypoxic conditions) males
# -------------------------------------------------------------------------------------
hyp.z.mal<-lm(z.value~cell.area*test.oxygen+fw*test.oxygen,
              data=male.h)

summary(hyp.z.mal)
# Coefficients:
#                       Estimate Std. Error t value Pr(>|t|)
# (Intercept)           -0.851506   7.599079  -0.112    0.914
# cell.area              0.038303   0.092440   0.414    0.693
# test.oxygen           -0.014021   0.462038  -0.030    0.977
# fw                     0.827461  20.551680   0.040    0.969
# cell.area:test.oxygen -0.002911   0.005621  -0.518    0.623
# test.oxygen:fw         0.421242   1.249579   0.337    0.748

anova(hyp.z.mal)
# Response: z.value
# Df Sum Sq Mean Sq F value  Pr(>F)  
# cell.area              1 2.0640  2.0640  2.3955 0.17265  
# test.oxygen            1 4.2364  4.2364  4.9167 0.06845 .
# fw                     1 0.9873  0.9873  1.1458 0.32559  
# cell.area:test.oxygen  1 0.1902  0.1902  0.2208 0.65503  
# test.oxygen:fw         1 0.0979  0.0979  0.1136 0.74752  
# Residuals              6 5.1698  0.8616

# -------------------------------------------------------------------------------------
# Lets try now by using the AIC weight approach for a list of models (Table 2)
# -------------------------------------------------------------------------------------
# CTMax under normoxic conditions

lm.ctmax1<-lm(ctmax~sex,data=tdt.n)#best model
summary(lm.ctmax1);anova(lm.ctmax1)

lm.ctmax2<-lm(ctmax~cell.area,data=tdt.n)

lm.ctmax3<-lm(ctmax~fw,data=tdt.n)

lm.ctmax4<-lm(ctmax~sex*cell.area,data=tdt.n)

lm.ctmax5<-lm(ctmax~sex*fw,data=tdt.n)

fit.list.ctmax<- list(lm.ctmax1,lm.ctmax2,lm.ctmax3,lm.ctmax4,lm.ctmax5)
fit.names.ctmax <-c("Sex","Cell area","Fresh mass","Sex * Cell area", "Sex * Fresh mass")

#compare using AICc
ctmax.norm<-aictab(fit.list.ctmax,fit.names.ctmax, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
ctmax.norm

# Model selection based on AICc:
#    
#                  K   AICc Delta_AICc AICcWt Cum.Wt     LL
# Sex              3 144.46       0.00   0.60   0.60 -68.90
# Sex * Cell area  5 147.39       2.94   0.14   0.74 -67.81
# Fresh mass       3 147.51       3.05   0.13   0.87 -70.42
# Sex * Fresh mass 5 147.93       3.47   0.11   0.97 -68.08
# Cell area        3 150.69       6.24   0.03   1.00 -72.01
#export table
write.csv(ctmax.norm,"Table 2.1 Model comparison for CTmax under normoxia.csv",row.names = F)
# -------------------------------------------------------------------------------------
# z under normoxic conditions

lm.z1<-lm(z.value~sex,data=tdt.n)#best model
summary(lm.z1);anova(lm.z1)

lm.z2<-lm(z.value~cell.area,data=tdt.n)


lm.z3<-lm(z.value~fw,data=tdt.n)


lm.z4<-lm(z.value~sex*cell.area,data=tdt.n)


lm.z5<-lm(z.value~sex*fw,data=tdt.n)


fit.list.z.value<- list(lm.z1,lm.z2,lm.z3,lm.z4,lm.z5)
fit.names.z.value <-c("Sex","Cell area","Fresh mass","Sex * Cell area", "Sex * Fresh mass")

#compare using AICc
z.norm<-aictab(fit.list.z.value,fit.names.z.value, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
z.norm

# Model selection based on AICc:
#    
#    K   AICc Delta_AICc AICcWt Cum.Wt     LL
# Sex              3 105.09       0.00   0.59   0.59 -49.21
# Fresh mass       3 107.36       2.27   0.19   0.78 -50.35
# Sex * Cell area  5 108.24       3.14   0.12   0.90 -48.24
# Sex * Fresh mass 5 108.98       3.89   0.08   0.98 -48.61
# Cell area        3 112.15       7.06   0.02   1.00 -52.74

#export table
write.csv(z.norm,"Table 2.2 Model comparison for z-value under normoxia.csv",row.names = F)

# -------------------------------------------------------------------------------------
# CTMax under two oxygen conditions

lm.ctmax1<-lm(ctmax~sex,data=tdt.h)

lm.ctmax2<-lm(ctmax~cell.area,data=tdt.h)

lm.ctmax3<-lm(ctmax~fw,data=tdt.h)

lm.ctmax4<-lm(ctmax~test.oxygen,data=tdt.h)#best model 1
summary(lm.ctmax4);anova(lm.ctmax4)

lm.ctmax5<-lm(ctmax~sex*cell.area,data=tdt.h)

lm.ctmax6<-lm(ctmax~sex*fw,data=tdt.h)

lm.ctmax7<-lm(ctmax~sex*test.oxygen,data=tdt.h)#best model 2
summary(lm.ctmax7);anova(lm.ctmax7)

lm.ctmax8<-lm(ctmax~cell.area*test.oxygen,data=tdt.h)

lm.ctmax9<-lm(ctmax~fw*test.oxygen,data=tdt.h)

lm.ctmax10<-lm(ctmax~sex*cell.area*test.oxygen,data=tdt.h)

lm.ctmax11<-lm(ctmax~sex*fw*test.oxygen,data=tdt.h)


fit.list.ctmax<- list(lm.ctmax1,lm.ctmax2,lm.ctmax3,lm.ctmax4,lm.ctmax5,
                      lm.ctmax6,lm.ctmax7,lm.ctmax8,lm.ctmax9,lm.ctmax10,
                      lm.ctmax11)
fit.names.ctmax <-c("Sex","Cell area","Fresh mass","Oxygen","Sex * Cell area", 
                    "Sex * Fresh mass","Sex * Oxygen","Cell area * Oxygen",
                    "Fresh mass * Oxygen","Sex * Cell area * Oxygen","Sex * Fresh mass * Oxygen")

#compare using AICc
ctmax.hypo<-aictab(fit.list.ctmax,fit.names.ctmax, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
ctmax.hypo

# Model selection based on AICc:
#    
#                           K  AICc Delta_AICc AICcWt Cum.Wt     LL
# Oxygen                    3 81.42       0.00   0.55   0.55 -37.11
# Sex * Oxygen              5 83.24       1.82   0.22   0.78 -34.95
# Sex                       3 86.02       4.60   0.06   0.83 -39.41
# Fresh mass * Oxygen       5 86.54       5.12   0.04   0.87 -36.60
# Cell area * Oxygen        5 86.94       5.52   0.03   0.91 -36.80
# Sex * Fresh mass          5 87.02       5.61   0.03   0.94 -36.85
# Sex * Cell area           5 87.92       6.51   0.02   0.96 -37.30
# Fresh mass                3 88.35       6.93   0.02   0.98 -40.57
# Cell area                 3 88.54       7.13   0.02   1.00 -40.67
# Sex * Fresh mass * Oxygen 9 92.79      11.38   0.00   1.00 -30.97
# Sex * Cell area * Oxygen  9 94.05      12.64   0.00   1.00 -31.60

#export Table 3
write.csv(ctmax.hypo,"Table 3.1 Model comparison for CTmax under two oxygen conditions.csv",row.names = F)

# -------------------------------------------------------------------------------------
# z under two oxygen conditions

lm.z1<-lm(z.value~sex,data=tdt.h)

lm.z2<-lm(z.value~cell.area,data=tdt.h)

lm.z3<-lm(z.value~fw,data=tdt.h)

lm.z4<-lm(z.value~test.oxygen,data=tdt.h)#best model 1
summary(lm.z4);anova(lm.z4)

lm.z5<-lm(z.value~sex*cell.area,data=tdt.h)

lm.z6<-lm(z.value~sex*fw,data=tdt.h)

lm.z7<-lm(z.value~sex*test.oxygen,data=tdt.h)#best model 2
summary(lm.z7);anova(lm.z7)

lm.z8<-lm(z.value~cell.area*test.oxygen,data=tdt.h)

lm.z9<-lm(z.value~fw*test.oxygen,data=tdt.h)

lm.z10<-lm(z.value~sex*cell.area*test.oxygen,data=tdt.h)

lm.z11<-lm(z.value~sex*fw*test.oxygen,data=tdt.h)

#list of models
fit.list.z<- list(lm.z1,lm.z2,lm.z3,lm.z4,lm.z5,
                      lm.z6,lm.z7,lm.z8,lm.z9,lm.z10,
                      lm.z11)
#names of models
fit.names.z <-c("Sex","Cell area","Fresh mass","Oxygen","Sex * Cell area", 
                    "Sex * Fresh mass","Sex * Oxygen","Cell area * Oxygen",
                    "Fresh mass * Oxygen","Sex * Cell area * Oxygen","Sex * Fresh mass * Oxygen")

#compare using AICc
z.hypo<-aictab(fit.list.z,fit.names.z, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
z.hypo

# Model selection based on AICc:
   
#                           K  AICc Delta_AICc AICcWt Cum.Wt     LL
# Oxygen                    3 63.18       0.00   0.44   0.44 -27.99
# Sex * Oxygen              5 63.58       0.40   0.36   0.80 -25.13
# Sex                       3 67.66       4.48   0.05   0.84 -30.23
# Fresh mass * Oxygen       5 67.71       4.52   0.05   0.89 -27.19
# Sex * Fresh mass          5 68.59       5.41   0.03   0.92 -27.63
# Cell area * Oxygen        5 68.66       5.47   0.03   0.95 -27.66
# Sex * Cell area           5 69.14       5.96   0.02   0.97 -27.90
# Fresh mass                3 70.30       7.12   0.01   0.98 -31.55
# Cell area                 3 70.88       7.70   0.01   0.99 -31.84
# Sex * Cell area * Oxygen  9 72.30       9.12   0.00   1.00 -20.72
# Sex * Fresh mass * Oxygen 9 72.43       9.25   0.00   1.00 -20.79

#export table
write.csv(z.hypo,"Table 3.2 Model comparison for z-value under two oxygen conditions.csv",row.names = F)
# -------------------------------------------------------------------------------------
# Testing the relationship between z and CTmax under normoxic
# -------------------------------------------------------------------------------------
t.off1<-lm(ctmax~z.value,data=tdt.n)
summary(t.off1)
anova(t.off1)
# -------------------------------------------------------------------------------------
# Testing the relationship between z and CTmax under two oxygen conditions
# -------------------------------------------------------------------------------------
t.off2<-lm(ctmax~test.oxygen*z.value,data=tdt.h)
summary(t.off2)
anova(t.off2)

visreg::visreg(t.off2,"z.value",by="test.oxygen",overlay=T)
# -------------------------------------------------------------------------------------
# FIGURE 6
# -------------------------------------------------------------------------------------
{
pdf("Figure 6 Trade-off between CTmax and sensitivity to temperature change.pdf",width = 10,height = 5)
png("Figure 6 Trade-off between CTmax and sensitivity to temperature change.png",width = 10,height = 5,units = "in",res = 300)
par(mfrow=c(1,2),tcl=-0.4, family="serif",
      omi=c(0,0,0,0))
plot(ctmax~z.value,data=tdt.n,las=1,xlab="z-value (°C)",ylab="CTmax (°C)",
col=c('#4DAC2660', '#A6761D60')[tdt.n$sex],cex=1.4, pch=16,cex.lab=1.2,
ylim=c(39,49),xlim=c(1,8))
# Add a legend
legend("topleft", legend=c("Females @ 21 kPa", "Males @ 21 kPa"),pch = 16,
       col=c('#4DAC2670', '#A6761D70'),bty="n",cex=0.8)

plot(ctmax~z.value,data=n,las=1,xlab="z-value (°C)",ylab="CTmax (°C)",
     col=c('#4DAC2660', '#A6761D60')[tdt.h$sex],cex=1.4, pch=16,cex.lab=1.2,
     ylim=c(39,49),xlim=c(1,8))
points(ctmax~z.value,data=h,las=1,xlab="z-value (°C)",ylab="CTmax (°C)",
     col=c('#4DAC2660', '#A6761D60')[tdt.h$sex],cex=1.4, pch=17,cex.lab=1.2,
     ylim=c(39,49),xlim=c(1,8))

# Add a legend
legend("topleft", legend=c("Females @ 21 kPa", "Males @ 21 kPa",
                           "Females @ 10 kPa", "Males @ 10 kPa"),pch = c(16,16,17,17),
       col=c('#4DAC2670', '#A6761D70','#4DAC2670', '#A6761D70'),bty="n",cex=0.8)

dev.off()
}
# -------------------------------------------------------------------------------------
# FIGURE 7
# -------------------------------------------------------------------------------------
{
pdf("Figure 7 Effect of sex on TDT parameters derived from normoxic conditions.pdf",width = 9,height = 5,useDingbats = FALSE)
png("Figure 7 Effect of sex on TDT parameters derived from normoxic conditions.png",width = 9,height = 5,units = "in",res = 300)
par(mfrow=c(1,2),tcl=-0.4, family="serif",omi=c(0,0,0,0))

plot(ctmax~sex,data=tdt.n,las=1,ylab="CTmax (°C)",xaxt='n',xlab="",axt='n',cex.lab=1.4,
     boxwex=0.5,col=c('#4DAC2660', '#A6761D60'),cex.axis=1.4,cex.lab=1.4,ylim=c(39,49))
axis(1,at=c(1,2),labels=c("Females","Males"),cex.axis=1.4)
plot(z.value~sex,data=tdt.n,las=1,ylab= "z-value (°C)",xlab="",xaxt='n',axt='n',cex.axis=1.4,
     boxwex=0.5, col=c('#4DAC2660', '#A6761D60'),cex.lab=1.4,ylim=c(1,8))
axis(1,at=c(1,2),labels=c("Females","Males"),cex.axis=1.4)
dev.off()
}
# -------------------------------------------------------------------------------------
# FIGURE 8
# -------------------------------------------------------------------------------------
{
pdf("Figure 8 Effect of sex on TDT parameters derived from two oxygen conditions.pdf",width = 9,height = 9,useDingbats = FALSE)
png("Figure 8 Effect of sex on TDT parameters derived from two oxygen conditions.png",width = 9,height = 9,units = "in",res = 300)
par(mfrow=c(2,2),tcl=-0.4, family="serif",omi=c(0,0,0,0))

par(mai=c(0.8,0.8,0,0))
plot(ctmax~sex,data=tdt.h,las=1,ylab="CTmax (°C)",xlab="",xaxt='n',axt='n',cex.lab=1.4,
   boxwex=0.5,col=c('#4DAC2660', '#A6761D60'),cex.axis=1.4,cex.lab=1.4,ylim=c(39,49))
axis(1,at=c(1,2),labels=c("Females","Males"),cex.axis=1.4)

par(mai=c(0.8,0.8,0,0))
plot(z.value~sex,data=tdt.h,las=1,ylab= "z-value (°C)",xlab="",xaxt='n',axt='n',cex.axis=1.4,
   boxwex=0.5, col=c('#4DAC2660', '#A6761D60'),cex.lab=1.4,ylim=c(1,8))
axis(1,at=c(1,2),labels=c("Females","Males"),cex.axis=1.4)

par(mai=c(0.6,0.8,0.1,0))
plot(ctmax~as.factor(test.oxygen),data=tdt.h,las=1,ylab="CTmax (°C)",xlab="",xaxt='n',axt='n',cex.lab=1.4,
     boxwex=0.5,col=c('#DCDCDC', '#FFFFFF'),cex.axis=1.4,cex.lab=1.4,ylim=c(39,49))
axis(1,at=c(1,2),labels=c("10 kPa","21 kPa"),cex.axis=1.4)

par(mai=c(0.6,0.8,0.1,0))
plot(z.value~as.factor(test.oxygen),data=tdt.h,las=1,ylab="z-value (°C)",xlab="",xaxt='n',axt='n',cex.lab=1.4,
     boxwex=0.5, col=c('#DCDCDC', '#FFFFFF'),cex.axis=1.4,cex.lab=1.4,ylim=c(1,8))
axis(1,at=c(1,2),labels=c("10 kPa","21 kPa"),cex.axis=1.4)
dev.off()
}

median.ctmax<-aggregate(ctmax~test.oxygen,data = tdt.h,median)
median.ctmax                

mean.ctmax<-cbind(aggregate(ctmax~test.oxygen,data = tdt.h,mean),
                  aggregate(ctmax~test.oxygen,data = tdt.h,sd))
mean.ctmax


median.ctmax<-aggregate(ctmax~test.oxygen,data = tdt.h,median)
median.ctmax                  

mean.z<-cbind(aggregate(z.value~test.oxygen,data = tdt.h,mean),
                  aggregate(z.value~test.oxygen,data = tdt.h,sd))
mean.z

################################################################################
##########################END OF SCRIPT#########################################
################################################################################